const testEnv: Record<string, string> = {
  POSTGRES_HOST: "localhost",
  POSTGRES_USER: "postgres",
  POSTGRES_PASSWORD: "postgres",
  POSTGRES_DB: "hypertube_test",
  POSTGRES_PORT: "5432",
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/hypertube_test",
  SERVER_URL: "http://localhost:3000",
  SERVER_PORT: "3000",
  CLIENT_URL: "http://localhost:3001",
  CLIENT_PORT: "3001",
  MAIL_FROM: "Hypertube <test@example.com>",
  MAIL_SMTP_HOST: "localhost",
  MAIL_SMTP_PORT: "1025",
  MAIL_SMTP_SECURE: "false",
  BETTER_AUTH_SECRET: "test-secret-at-least-32-chars-long",
  BETTER_AUTH_URL: "http://localhost:3000",
  GOOGLE_CLIENT_ID: "test-google-id",
  GOOGLE_CLIENT_SECRET: "test-google-secret",
  GITHUB_CLIENT_ID: "test-github-id",
  GITHUB_CLIENT_SECRET: "test-github-secret",
  DISCORD_CLIENT_ID: "test-discord-id",
  DISCORD_CLIENT_SECRET: "test-discord-secret",
  SCHOOL_42_CLIENT_ID: "test-42-id",
  SCHOOL_42_CLIENT_SECRET: "test-42-secret",
  TORRENT_PORT: "51413",
  S3_ENDPOINT: "localhost",
  S3_PORT: "9000",
  S3_URL: "http://localhost:9000",
  S3_ROOT_USER: "s3admin",
  S3_ROOT_PASSWORD: "s3password",
  TMDB_TOKEN: "test-tmdb-token",
  PROWLARR_URL: "http://localhost:9696",
  PROWLARR_API_KEY: "test-prowlarr-api-key",
  PROWLARR_PORT: "9696",
  PROWLARR_INDEXER_IDS: "",
  SUBTITLE_PROXY_URL: "http://localhost:3042",
  SUBTITLE_PROXY_PORT: "3042",
  REDIS_HOST: "localhost",
  REDIS_PORT: "6379",
  VPN_IS_ACTIVE: "true",
  NODE_ENV: "DEV",
};

for (const [key, value] of Object.entries(testEnv)) {
  process.env[key] = value;
}
