const testEnv: Record<string, string> = {
  POSTGRES_HOST: "localhost",
  POSTGRES_USER: "postgres",
  POSTGRES_PASSWORD: "postgres",
  POSTGRES_DB: "hypertube_test",
  POSTGRES_PORT: "5432",
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/hypertube_test",
  SERVER_URL: "http://localhost:3000",
  SERVER_PORT: "3000",
  CLIENT_URL: "http://localhost:3001",
  CLIENT_PORT: "3001",
  MAIL_FROM: "Hypertube <test@example.com>",
  MAIL_SMTP_HOST: "localhost",
  MAIL_SMTP_PORT: "1025",
  MAIL_SMTP_SECURE: "false",
  BETTER_AUTH_SECRET: "test-secret-at-least-32-chars-long",
  BETTER_AUTH_URL: "http://localhost:3000",
  GOOGLE_CLIENT_ID: "test-google-id",
  GOOGLE_CLIENT_SECRET: "test-google-secret",
  GITHUB_CLIENT_ID: "test-github-id",
  GITHUB_CLIENT_SECRET: "test-github-secret",
  DISCORD_CLIENT_ID: "test-discord-id",
  DISCORD_CLIENT_SECRET: "test-discord-secret",
  SCHOOL_42_CLIENT_ID: "test-42-id",
  SCHOOL_42_CLIENT_SECRET: "test-42-secret",
  TRANSMISSION_HOST: "localhost",
  TRANSMISSION_RCP_PORT: "9091",
  TRANSMISSION_TORRENT_PORT: "51413",
  MINIO_ENDPOINT: "localhost",
  MINIO_PORT: "9000",
  MINIO_URL: "http://localhost:9000",
  MINIO_ROOT_USER: "minioadmin",
  MINIO_ROOT_PASSWORD: "minioadmin",
  TMDB_TOKEN: "test-tmdb-token",
  YTS_API_URL: "https://yts.mx/api/v2",
  YTS_PROXY_URL: "http://localhost:3042",
  YTS_PROXY_PORT: "3042",
  REDIS_HOST: "localhost",
  REDIS_PORT: "6379",
  VPN_IS_ACTIVE: "true",
  NODE_ENV: "DEV",
};

for (const [key, value] of Object.entries(testEnv)) {
  process.env[key] = value;
}
