services:
  vpn:
    ports:
      - "${TRANSMISSION_RCP_PORT}:${TRANSMISSION_RCP_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}/udp"
      - "${PROWLARR_PORT}:${PROWLARR_PORT}"
      - "${SUBTITLE_PROXY_PORT}:${SUBTITLE_PROXY_PORT}"
