services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:17
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - hypertube_data:/var/lib/postgresql/data
    networks:
      - hypertube-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: hypertube_adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - hypertube-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  hypertube_data:

networks:
  hypertube-network:
    external: true
