services:
  scrapper:
    container_name: hypertube-scrapper-prod
    build:
      context: .
      dockerfile: ./apps/scrapper/Dockerfile.prod
    env_file: .env
    environment:
      - REDIS_HOST=redis
    command: bash -c "pnpm build:workers:scrapper && pnpm start:workers:scrapper"
    networks:
      - hypertube-network

  downloader:
    container_name: hypertube-downloader-prod
    build:
      context: .
      dockerfile: ./apps/downloader/Dockerfile.prod
    env_file: .env
    environment:
      - REDIS_HOST=redis
    command: bash -c "pnpm build:workers:downloader && pnpm start:workers:downloader"
    networks:
      - hypertube-network

networks:
  hypertube-network:
    external: true