services:
  db:
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  adminer:
    ports:
      - "8080:8080"

  transmission:
    ports:
      - "${TRANSMISSION_RCP_PORT}:${TRANSMISSION_RCP_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}/udp"

  redis:
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
