services:
  adminer:
    container_name: hypertube_adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - hypertube-network

  redisinsight:
    container_name: hypertube_redisinsight
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/data
    networks:
      - hypertube-network

  bull-board:
    container_name: hypertube_bull-board
    image: venatum/bull-board:3.3
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 5541:3000
    networks:
      - hypertube-network

networks:
  hypertube-network:
    external: true

volumes:
  redisinsight:
