services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:17-bookworm
    env_file: .env
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - hypertube_data:/var/lib/postgresql/data
    networks:
      - hypertube-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: hypertube_adminer
    image: adminer
    ports:
      - 8080
    networks:
      - hypertube-network
    depends_on:
      db:
        condition: service_healthy

  transmission:
    container_name: transmission
    image: linuxserver/transmission
    ports:
      - ${TRANSMISSION_RCP_PORT}
      - ${TRANSMISSION_TORRENT_PORT}
      - ${TRANSMISSION_TORRENT_PORT}/udp
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
    volumes:
      - ./apps/server/downloads:/downloads
    networks:
      - hypertube-network

  redis:
    container_name: hypertube_redis
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}
    networks:
      - hypertube-network

volumes:
  hypertube_data:

networks:
  hypertube-network:
    external: true
