services:
  vpn:
    image: alpine:3.21
    container_name: vpn
    command: sleep infinity
    ports:
      - "${TRANSMISSION_RCP_PORT}:${TRANSMISSION_RCP_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}/udp"
      - "${PROWLARR_PORT}:${PROWLARR_PORT}"
      - "${SUBTITLE_PROXY_PORT}:${SUBTITLE_PROXY_PORT}"
    networks:
      - hypertube-network

networks:
  hypertube-network:
    external: true
