services:
  vpn:
    ports:
      - "${TRANSMISSION_RCP_PORT}:${TRANSMISSION_RCP_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}/udp"
      - "${YTS_PROXY_PORT}:${YTS_PROXY_PORT}"
