services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:17-bookworm
    env_file: .env
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - hypertube_data:/var/lib/postgresql/data
    networks:
      - hypertube-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  transmission:
    container_name: transmission
    image: linuxserver/transmission:4.1.0
    env_file: .env
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
    volumes:
      - ./apps/downloader/config/settings.json:/config/settings.json:ro
      - downloads_transmission:/downloads-transmission
    network_mode: container:vpn

  redis:
    container_name: hypertube_redis
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}
    networks:
      - hypertube-network

  minio:
    container_name: hypertube_minio
    image: minio/minio:latest
    ports:
      - 9000
      - 9001
    networks:
      - hypertube-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - hypertube-network
    entrypoint: /bin/sh
    command:
      - -c
      - |
        until mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do sleep 1; done
        mc mb -p local/movies || true
        mc mb -p local/images || true
        mc anonymous set download local/images
    restart: no

volumes:
  hypertube_data:
  minio_data:
  downloads_transmission:
    name: hypertube_downloads_transmission

networks:
  hypertube-network:
    external: true
