services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:17-bookworm
    env_file: .env
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - hypertube_data:/var/lib/postgresql/data
    networks:
      - hypertube-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  transmission:
    container_name: transmission
    image: linuxserver/transmission
    env_file: .env
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
    volumes:
      - ./apps/downloader/config/settings.json:/config/settings.json:ro
      - movies_data:/downloads
      - movies_data_transmission:/downloads-transmission
    network_mode: container:vpn

  redis:
    container_name: hypertube_redis
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}
    networks:
      - hypertube-network

volumes:
  hypertube_data:
  movies_data:
  movies_data_transmission:

networks:
  hypertube-network:
    external: true
