services:
  app:
    container_name: hypertube-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - NODE_ENV=DEV
      - PUPPETEER_SKIP_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - REDIS_HOST=redis
      - TRANSMISSION_HOST=transmission
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${CLIENT_PORT}:${CLIENT_PORT}" # for development only
    volumes:
      - ./node_modules:/hypertube/node_modules
      - ./apps:/hypertube/apps
    command: bash -c "umask 000 && pnpm i --frozen-lockfile && chmod 777 -R /hypertube/apps/server/node_modules && chmod 777 -R /hypertube/apps/client/node_modules && chmod 777 -R /hypertube/apps/libs/node_modules && chmod 777 -R /hypertube/apps/server-core/node_modules && chmod 777 -R /hypertube/apps/downloader/node_modules && chmod 777 -R /hypertube/apps/scheduler/node_modules && chmod 777 -R /hypertube/node_modules && pnpm --filter server-core prisma:migrate:reset && pnpm --filter server-core prisma:migrate && pnpm dev"
    networks:
      - hypertube-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hypertube-network:
    external: true
