services:
  db:
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  transmission:
    ports:
      - "${TRANSMISSION_RCP_PORT}:${TRANSMISSION_RCP_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}"
      - "${TRANSMISSION_TORRENT_PORT}:${TRANSMISSION_TORRENT_PORT}/udp"

  redis:
    ports:
      - "2424:6379"
