services:
  app:
    container_name: hypertube-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - NODE_ENV=DEV
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${CLIENT_PORT}:${CLIENT_PORT}" # for development only
    volumes:
      - ./apps:/hypertube/apps
      - ./node_modules:/hypertube/node_modules
      - ./apps/server/node_modules:/hypertube/apps/server/node_modules
      - ./apps/client/node_modules:/hypertube/apps/client/node_modules
      - ./apps/libs/node_modules:/hypertube/apps/libs/node_modules
    command: bash -c "umask 000 && pnpm i --frozen-lockfile && chmod 777 -R /hypertube/apps/server/node_modules && chmod 777 -R /hypertube/apps/client/node_modules && chmod 777 -R /hypertube/apps/libs/node_modules && chmod 777 -R /hypertube/node_modules && pnpm --filter server prisma:migrate && pnpm dev"
    networks:
      - hypertube-network
    healthcheck:
      test: ["CMD", "curl", "-f", "${SERVER_URL}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hypertube-network:
    external: true
