services:
  app:
    container_name: hypertube
    build: .
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - NODE_ENV=PROD
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: bash -c "pnpm --filter server prisma:migrate && pnpm build && pnpm start"
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    networks:
      - hypertube-network
    healthcheck:
      test: ["CMD", "curl", "-f", "${SERVER_URL}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hypertube-network:
    external: true
