services:
  scrapper:
    container_name: hypertube-scrapper-dev
    build:
      context: .
      dockerfile: ./apps/scrapper/Dockerfile.dev
    env_file: .env
    command: bash -c "umask 000 && pnpm i --frozen-lockfile && chmod 777 -R /hypertube/apps/scrapper/node_modules && pnpm dev:workers:scrapper"
    networks:
      - hypertube-network

  downloader:
    container_name: hypertube-downloader-dev
    build:
      context: .
      dockerfile: ./apps/downloader/Dockerfile.dev
    env_file: .env
    command: bash -c "umask 000 && pnpm i --frozen-lockfile && chmod 777 -R /hypertube/apps/downloader/node_modules && pnpm dev:workers:downloader"
    networks:
      - hypertube-network

networks:
  hypertube-network:
    external: true