services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file: .env
    ports:
      - ${TRANSMISSION_RCP_PORT}
      - ${TRANSMISSION_TORRENT_PORT}
      - ${TRANSMISSION_TORRENT_PORT}/udp
      - ${YTS_PROXY_PORT}
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${VPN_COUNTRY:-Switzerland}
      - OPENVPN_MSSFIX=1280
      - OPENVPN_MTU=1300
    networks:
      - hypertube-network

networks:
  hypertube-network:
    external: true
