services:
  app:
    container_name: hypertube-prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - TRANSMISSION_HOST=transmission
      - NODE_ENV=PROD
      - PUPPETEER_SKIP_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: bash -c "pnpm lint && pnpm --filter server prisma:migrate:reset && pnpm --filter server prisma:migrate && pnpm --filter server prisma:seed && pnpm build && pnpm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "${HOSTNAME}:${SERVER_PORT}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
