FROM node:22 AS builder

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /hypertube

COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY .env ./
COPY eslint.config.js ./

COPY apps/subtitle-proxy ./apps/subtitle-proxy
COPY packages/libs ./packages/libs
COPY packages/server-core ./packages/server-core

RUN pnpm i --frozen-lockfile
RUN pnpm lint
RUN pnpm --filter server-core prisma:generate
RUN pnpm build:subtitle-proxy

FROM node:22-alpine AS runner

RUN apk add --no-cache chromium nss freetype harfbuzz ttf-freefont

WORKDIR /hypertube

COPY --from=builder /hypertube/node_modules ./node_modules
COPY --from=builder /hypertube/apps/subtitle-proxy/node_modules ./apps/subtitle-proxy/node_modules
COPY --from=builder /hypertube/packages/libs/node_modules ./packages/libs/node_modules
COPY --from=builder /hypertube/packages/server-core/node_modules ./packages/server-core/node_modules

COPY --from=builder /hypertube/apps/subtitle-proxy/dist ./apps/subtitle-proxy/dist
COPY --from=builder /hypertube/packages/libs/dist ./packages/libs/dist
COPY --from=builder /hypertube/packages/server-core/dist ./packages/server-core/dist

COPY --from=builder /hypertube/apps/subtitle-proxy/package.json ./apps/subtitle-proxy/package.json
COPY --from=builder /hypertube/packages/libs/package.json ./packages/libs/package.json
COPY --from=builder /hypertube/packages/server-core/package.json ./packages/server-core/package.json

WORKDIR /hypertube/apps/subtitle-proxy

CMD ["node", "./dist/apps/subtitle-proxy/src/main.js"]
