FROM node:22

# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /hypertube

# Copy root files
COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY .env ./
COPY eslint.config.js ./

COPY apps/server ./apps/server
COPY apps/client ./apps/client
COPY apps/libs ./apps/libs
COPY apps/server-core ./apps/server-core

RUN pnpm i --frozen-lockfile
RUN pnpm lint
RUN pnpm --filter server-core prisma:generate
RUN pnpm build:app

CMD ["pnpm", "start:app"]