FROM node:22 AS builder

# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /hypertube

# Copy root files
COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY .env ./
COPY patches ./patches

COPY apps/client ./apps/client
COPY packages/libs ./packages/libs

RUN pnpm i --frozen-lockfile
RUN pnpm build


FROM nginx:alpine AS runner

RUN apk add --no-cache curl

COPY --from=builder --chown=nginx:nginx /hypertube/apps/client/dist /usr/share/nginx/html
COPY --from=builder --chown=nginx:nginx /hypertube/apps/client/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/cache/nginx/client_temp \
    /var/cache/nginx/proxy_temp \
    /var/cache/nginx/fastcgi_temp \
    /var/cache/nginx/uwsgi_temp \
    /var/cache/nginx/scgi_temp \
    && chown -R nginx:nginx /var/cache/nginx /var/log/nginx

USER nginx

CMD ["nginx", "-g", "daemon off;"]