FROM node:22 AS builder

# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /hypertube

# Copy root files
COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY .env ./

COPY apps/client ./apps/client
COPY packages/libs ./packages/libs

RUN pnpm i --frozen-lockfile
RUN pnpm build


FROM nginx:alpine AS runner

WORKDIR /hypertube

COPY --from=builder /hypertube/apps/client/dist ./apps/client/dist
COPY --from=builder /hypertube/apps/client/nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]