FROM node:22

# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /hypertube

# Copy root files
COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY .env ./
COPY eslint.config.js ./

COPY packages/libs ./packages/libs
COPY packages/server-core ./packages/server-core
COPY apps/downloader ./apps/downloader

RUN pnpm i --frozen-lockfile
RUN pnpm lint
RUN pnpm --filter server-core prisma:generate
RUN pnpm build:downloader

CMD ["pnpm", "start:downloader"]