FROM node:22 AS builder

# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /hypertube

# Copy root files
COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY .env ./
COPY eslint.config.js ./

COPY packages/libs ./packages/libs
COPY packages/server-core ./packages/server-core
COPY apps/downloader ./apps/downloader

RUN pnpm i --frozen-lockfile
RUN pnpm lint
RUN pnpm --filter server-core prisma:generate
RUN pnpm build:downloader

FROM node:22-slim AS runner

RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /hypertube

COPY --from=builder /hypertube/node_modules ./node_modules
COPY --from=builder /hypertube/apps/downloader/node_modules ./apps/downloader/node_modules
COPY --from=builder /hypertube/packages/libs/node_modules ./packages/libs/node_modules
COPY --from=builder /hypertube/packages/server-core/node_modules ./packages/server-core/node_modules

COPY --from=builder /hypertube/apps/downloader/dist ./apps/downloader/dist
COPY --from=builder /hypertube/packages/libs/dist ./packages/libs/dist
COPY --from=builder /hypertube/packages/server-core/dist ./packages/server-core/dist

COPY --from=builder /hypertube/apps/downloader/package.json ./apps/downloader/package.json
COPY --from=builder /hypertube/packages/libs/package.json ./packages/libs/package.json
COPY --from=builder /hypertube/packages/server-core/package.json ./packages/server-core/package.json

WORKDIR /hypertube/apps/downloader

CMD ["node", "./dist/main.js"]