export * from "./accounts.schema.js";
export * from "./comments.schema.js";
export * from "./credential.schema.js";
export * from "./image.schema.js";
export * from "./likes.schema.js";
export * from "./movie.schema.js";
export * from "./notifications.schema.js";
export * from "./session.schema.js";
export * from "./user.schema.js";
