FROM node:22 AS builder

# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /hypertube

# Copy root files
COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY .env ./
COPY eslint.config.js ./

COPY apps/yts-api-proxy ./apps/yts-api-proxy
COPY packages/libs ./packages/libs
COPY packages/server-core ./packages/server-core

RUN pnpm i --frozen-lockfile
RUN pnpm --filter server-core prisma:generate
RUN pnpm lint
RUN pnpm build:yts-api-proxy

FROM node:22-alpine AS runner

RUN apk add --no-cache chromium nss freetype harfbuzz ttf-freefont

WORKDIR /hypertube

COPY --from=builder --chown=node:node /hypertube/node_modules ./node_modules
COPY --from=builder --chown=node:node /hypertube/apps/yts-api-proxy/node_modules ./apps/yts-api-proxy/node_modules
COPY --from=builder --chown=node:node /hypertube/packages/libs/node_modules ./packages/libs/node_modules
COPY --from=builder --chown=node:node /hypertube/packages/server-core/node_modules ./packages/server-core/node_modules

COPY --from=builder --chown=node:node /hypertube/apps/yts-api-proxy/dist ./apps/yts-api-proxy/dist
COPY --from=builder --chown=node:node /hypertube/packages/libs/dist ./packages/libs/dist
COPY --from=builder --chown=node:node /hypertube/packages/server-core/dist ./packages/server-core/dist

COPY --from=builder --chown=node:node /hypertube/apps/yts-api-proxy/package.json ./apps/yts-api-proxy/package.json
COPY --from=builder --chown=node:node /hypertube/packages/libs/package.json ./packages/libs/package.json
COPY --from=builder --chown=node:node /hypertube/packages/server-core/package.json ./packages/server-core/package.json

WORKDIR /hypertube/apps/yts-api-proxy

USER node

CMD ["node", "./dist/main.js"]